### ISSUE TITLE
Discharge (退院) does not match data set

### ISSUE THREAD

**Issue by VennieSo** [tokyo-metropolitan-gov/covid19#1310] opened 2020-03-13 05:05 UTC
Since March 9, there has been 24 patients marked as "discharged" in the dataset. But the summary table continues to say only 22 discharged.

Please refer to:

退院済フラグ from the [source data set](https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068)

退院 under "patients" in [data.json](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/data.json#L825)

**Comment by kaizumaki** [comment] 2020-03-13 05:09
@VennieSo Thanks for the report! We will examine.

**Comment by ocean3fish** [comment] 2020-03-13 05:24
@VennieSo 
That is because the number of discharge due to death included in the "Confirmed patient attributes" table.
<img width="552" alt="スクリーンショット 2020-03-13 14 17 53" src="https://user-images.githubusercontent.com/4206675/76592100-a2f72780-6535-11ea-8e32-6906e1840da0.png">

**Comment by halsk** [comment] 2020-03-16 04:19
Let me close this issue. Please re-open if you have some additional questions.

**Closed by halsk** 2020-03-16 04:19 UTC
